dist: bionic
language: python
cache: pip
matrix:
    include:
    - python: '3.7'
      env: TEST_SUITE=suite_3_7
    - python: '3.8-dev'
      env: TEST_SUITE=suite_3_8_dev
before_install:
  - pip install -r requirements.txt
install:
- python setup.py test
script:
- python theHarvester.py -d metasploit.com -b baidu,bing,crtsh,dnsdumpster,dogpile,duckduckgo,exalead,linkedin,netcraft,otx,intelx,threatcrowd,trello,twitter,virustotal,yahoo -l 200
- pytest
- flake8 . --count --show-source --statistics
#- mypy --pretty *.py
notifications:
  email: false
  slack:
    rooms:
      secure: qk0tYyEnuOZ5uEFS7VUQ0BJQP8h1O1D6mmK3u/2ttzJ87hfHzZozhCoUiWNySIz66B8DEy77SGdKAT/VXjJQKtKEKg8pHrHenqEMk0XDOloEBd1AoIVfrBd5I9neE6EN8DDX7PhaEs7tk1PX3OEDOEmuLabToiAtWILnCeChOUUy/cTWgpv5lDsafpsvzmU95EG/q5e6PvkudPW5S8sAcw/HN/Lt35yQFQFsX3J8rz5V1fESsn3kcOD/zrp9Yx/UC4M9cvfQEJ1R6ILrVYoSUZhvFZqrfgDvxrVX8PxkFUJxZX5rxx4/fKi3aAXX49rc7Cx0eKTE+fy422p2psh4pNITge4Lm6n1VGFSlAqfEBjcHMRN+SmNUbGPCj2aRqKR853rL+nE26AIECOehKIA3bxTcWvpKyydc7MryiypJ0ZCZWlubQGDf7ck3p9alCmPl9oVZ5H5Zy3AcMWezJYJRdwQchXTt3tG5xCQ8PCvz5aMWwHYDxsknB288MUExjazjgdU2TQKeZlK0AVqgEis50aAVpKPZ8F9+kXn3eGi4H1I8o9YepwVE7S0LACkt8mjN+LMa5EKt33O8FSHe13ywXhX9vFoW6rhLMypcPJ3dTpZ9zDUMO/eBpZsn0gaJPM++NGaGmLE/TQUVvw939GFFyOOU63i+aSMnmMpSsNyfn0=
    on_success: always
    on_failure: always
    template:
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Message: %{message}"
      - "By: %{author}"