dist: xenial
language: python
python:
- '3.6'
- '3.7'
- '3.8-dev'
install:
- pip install -r requirements.txt
script:
- pytest

notifications:
  slack:
    rooms:
      - secure: cx6grPu1CenA8cgxHTQBWBsxxhm2bZSJkWMHylvusnTGWWa3/Q/hr2dWQ1NzywY3n0UK0kqufuFl0NpJEfLpihSlEkDUlaBiYdAIr0EpBmCNNATSY/LPvaHJcca3jtlVuCaya6xU1JEbEQlXO62wU7XNjngbYgu3BkduPzip5nDVoNdq+4wtDtzIPXg1oEuOrQONmvQAtRZxuaN5a4vTiV2x0hOi0CSK0Z0nhjRVFF7XqFn5a00V4UaBBAHpD+2lW5W9FAKU1NmW3faAkm+MCqx6cTb/QXk5jRz5cNgYh7AzqXvL4D4KcWmKmumpW2prx37klXqtntHinYwQ+DBj723q1bRHvinKkQIVkA71QFfFuq94T4yr+4ra4mL4c2Oq+lIqBKNHHy9DfaHKCTlQ1+0ND0pnXt2XPrqHtg7pYl3XCbeeJFCYDua+CL2SPEE0RJ8PAkK8TVo0zYBXzveb+ZtbbrsJDhgjj+OoViIkzpDys/2vn0vHZ1aDzr5qNLkPi1r37JfP0VtARzWfaqrGavvP1i3ebG37q4uPuyUPUftpRGeu4RXc2D0+r1WsiR/PDNRqee8rV+ULyVh55rB9tb2jyTiLk8ALFke8PcC9nc68a7OLV5J7e3ndxIhlY7TkagDScW7yh48UBoO1xn1y12DM6PZoOSaX/rXBWvOCi4g=
    on_success: always
    on_failure: always
    on_pull_requests: true