dist: xenial
language: python
python:
- '3.6'
- '3.7'
- '3.8-dev'
install:
- pip install -r requirements.txt
script:
- pytest
notifications:
  email: false
  slack:
    rooms:
      secure: eSz43Byhtf5EnrxVWNS8DThHh5j1K3AfyGWdfSJpdqrw7FgvXq3xurwg9c3JzKImRkdPTMaym0WYNPWiW0wIPmzSZhc2d3eT1AI48WzKCj4HGvszzCN1SS6hhoqO2bBoXTM7Rr/eNrVSL0wjKS3X0bv2IjKkWx9nn1rLDtzU4CMV7+yVoWrruIxh6ck3GAXmNKPPXNen91Q7f8K0yG5JKVaWuxGoop7hj0eqgEkfrTouCSH8pes8o3TVArR1cQZAQUFW43lISQGodd8LaIPrckq+FVOJt5fddCFTDpPQW0mdobKN0SjYF0mxL8fiI0LYWq4ncxR44WV3dOXZCi5uNf1C9Q+eKANuSGCgVv0+u63iO/iWr8yM4wWetiihBO/oaLoqvLchSRrfEO3x5FFhIGH3d946k4DpYSWBtKCBUNE7lyvzBkR5LUhUzAvMSSfdMsxuhuDs+Bwfou9Dqlmf0TJYDlaitGubh+nsFR3BFt19kMX/h3Ay/+6VBwnu0NGnnO9JNmtAnoRm4P5taZvwJQtd3ixazSpJvQ6srq5umuILuOthk+8M18VWdaCSOJmh6W2USFtfJfaXIOh2UjyDNGvJOYyRdGT0Gn28fqvRDRA4HOkLgu4BT5eEq4BGxdaQc0KtPYx6L0ua0g6pTREwl9gpWN7sy1NlxFXpA4BZMw0=
    on_success: always
    on_failure: always
    template:
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Message: %{message}"