dist: xenial
language: python
python:
- '3.6'
- '3.7'
- '3.8-dev'
install:
- pip install -r requirements.txt
script:
- pytest
notifications:
  email: false
  slack:
    rooms:
      secure: gBBkGz2eFkcGdPEF87FNthrEJld1iit91Au7uBJ7ThZnDNXW8nD2SQKoA3bMtYIQMJAYc3VVrjSmkaKxmGkyEnwJpAXZk8rUY6vhA/BRS6y8vOlmBRKnXmiDaJA26ClB5ACtBdktlBxAOy7i2wcA0//JAHgQnneymIU8J3oiOD9TI/t3kVSd1cY+SMEvB1CwujY9DIgT/KR+gAHXGVemsUMeiNM2aWP4MmOJ1mFvGP6qj7CvwakU3xO/8SC6LzCTJU5ebCGsd2+KGGNtz3DZAewnr7L5OaHxjOWEvt+qu5XS+YLiAYmZwB6IvI1SRJWCQukSaFJoi3jDItV2l7O/udzSLF3Pq5NRjbn0oNv/vYo4HaAlNATzG/Wa47tkoRXeEL2t0qMThjiYcOsU/gMA/1mHhE11/I7OMTiCCt7O/ltwKATRJRjhmL+h9xb7WUTUKxdOQvP78bqBy364hba5KnecF7oEG2Vl9hCGS1exABh0Fl6kQbX3CHXYJ5pZ282xTalAHvq7XiyWpvkZqv4hFfahZcqCBwQEERcJtCXELXzbtu0IncAcVa31e6CZv12UsBu9FKcsC8mws41IApwD97HJmZOi/H968jzaHm/MrP/eSCyLUGJ3gcFE17z6rxt3peXYe9vVrEyNVP5iUHWMNcQ8kK1uDXPzaWEDaf1gYPs=
    on_success: always
    on_failure: always
    template:
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Message: %{message}"